<Project>
  <PropertyGroup>
    <Version>1.1.2</Version>
    <AssemblyVersion>1.1.2.0</AssemblyVersion>
    <FileVersion>1.1.2.0</FileVersion>
    <Product>PhotoForge</Product>
    <Company>PhotoForge Project</Company>
    <Authors>Ramana Reddy Chamakura</Authors>
    <Copyright>Copyright © 2026 PhotoForge Contributors</Copyright>
    <RepositoryUrl>https://github.com/ramanacr/photo-forge</RepositoryUrl>
  </PropertyGroup>
</Project>