<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <RootNamespace>PhotoForge.Matching</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\PhotoForge.Core\PhotoForge.Core.csproj" />
    <ProjectReference Include="..\PhotoForge.Metadata\PhotoForge.Metadata.csproj" />
    <ProjectReference Include="..\PhotoForge.Imaging\PhotoForge.Imaging.csproj" />
  </ItemGroup>

</Project>
