<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net9.0;netstandard2.0</TargetFrameworks>
    <RootNamespace>PhotoForge.Metadata</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\PhotoForge.Core\PhotoForge.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MetadataExtractor" Version="2.8.1" />
    <PackageReference Include="System.Text.Json" Version="9.0.0" />
  </ItemGroup>

</Project>
